#!/data/data/com.termux/files/usr/bin/bash
if [ "$RUST_LOG" = debug ]; then
  set -x
fi

set -euo pipefail
dir="$PWD"
rerun="bash callback '$1' '$2' '$3' '$4' '$5'"

if [ "$5" = 1 ]; then
  pre='Over '
else
  pre=
fi

url="https://www.pixiv.net/i/$2"
action="am start -a android.intent.action.VIEW -d $url"

if [ -f showimg ]; then
  flags=(--image-path "$dir/img.jpg" --button1-action "cd '$dir';rm showimg;$rerun")
else
  flags=(--button1-action "cd '$dir';:>showimg;$rerun")
fi

flags+=(--ongoing --alert-once \
  -t "$pre$1 illusts" -c '' --icon favorite \
  --button1 "SINCE = $3   ($4)" \
  --action "$action<'$dir/notify'" \
  --on-delete ":<'$dir/notify'")

dist="$1"
n=$((1 + dist / 30))

for (( i = 0; i < n; i++ )); do
  timeout -v 30 termux-notification -i krrpxv$i --group krrpxv$i "${flags[@]}" &
done

for (( i = n; i < 4; i++ )); do
  timeout -v 30 termux-notification-remove krrpxv$i &
done

wait
